version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.WriteString
        - '(*github.com/cespare/xxhash/v2.Digest).WriteString'
        - '(*github.com/cespare/xxhash/v2.Digest).Write'
        - '(net/http.ResponseWriter).Write'
        - '(*net/http.ResponseController).Flush'
        - '(net.Listener).Close'
        - '(io.Closer).Close'
        - '(*os.File).Close'
        - 'github.com/prometheus/common/expfmt.MetricFamilyToText'

